version: "3.8"
services:

  nodered:
    container_name: Node-red
    image: nodered/node-red:latest 
    restart: always
    ports:
      - 1880:1880

  mosquitto:
        image: eclipse-mosquitto:2
        ports:
            - 1883:1883
            - 8883:8883
            - 9001:9001
        volumes:
            - C:\mosquitto\config:/mosquitto/config
            - C:\mosquitto\data:/mosquitto/data
        networks:
            - mosquitto
networks:
    mosquitto:
        name: mosquitto
        driver: bridge