version: "3.8"
services:

  nodered:
    container_name: Node-red
    image: nodered/node-red:latest 
    restart: always
    ports:
      - 1880:1880

  mongodb:
    container_name: mongodb
    image: mongo:6-jammy
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - C:\dbdata6:/data/db

  mosquitto:
        container_name: mosquittomqtt
        image: eclipse-mosquitto:2
        restart: always
        ports:
            - 1883:1883
        volumes:
            - C:\mosquitto\config:/mosquitto/config
            - C:\mosquitto\data:/mosquitto/data
        networks:
            - mosquitto
networks:
    mosquitto:
        name: mosquitto
        driver: bridge